Bugfix: `TypeError: o.getAttribute is not a function converse-chatview.js`
can cause messages to not appear.

* Check against null not Element.
* Avoid iterating over non-Element nodes